<a href="https://colab.research.google.com/github/sunam128/Algorithm-Recommendation/blob/main/AlgorithmRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
file=files.upload()

Saving Pokemon Data.csv to Pokemon Data.csv

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder #convert categorical columns to numerical columns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Data Exploration
* To understand what the data is about.

In [4]:
#load the data
ds=pd.read_csv("Pokemon Data.csv")
ds.head()

   #                   Name Type 1  ... Speed  Generation  Legendary
0  1              Bulbasaur  Grass  ...    45           1      False
1  2                Ivysaur  Grass  ...    60           1      False
2  3               Venusaur  Grass  ...    80           1      False
3  3  VenusaurMega Venusaur  Grass  ...    80           1      False
4  4             Charmander   Fire  ...    65           1      False

[5 rows x 12 columns]

In [5]:
#dataset information
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [6]:
ds.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [7]:
#check for duplicates
ds.duplicated().sum()

np.int64(0)

# Data Preprocessing
* Prepare the data for analysis.

In [8]:
#dropping null values
ds.dropna(inplace=True)

In [10]:
#convert categorical columns to numerical
ls=LabelEncoder()
ds["Type 1"]=ls.fit_transform(ds["Type 1"])
ds["Type 2"]=ls.fit_transform(ds["Type 2"])
ds["Legendary"]=ls.fit_transform(ds["Legendary"])

In [14]:
#drop unecessary/unique columns
ds.drop('#',axis=1,inplace=True)

In [15]:
ds.head()

   Type 1  Type 2  HP  Attack  ...  Sp. Def  Speed  Generation  Legendary
0       0      13  45      49  ...       65     45           1          0
1       0      13  60      62  ...       80     60           1          0
2       0      13  80      82  ...      100     80           1          0
3       0      13  80     100  ...      120     80           1          0
6       0       7  78      84  ...       85    100           1          0

[5 rows x 10 columns]

In [18]:

#feature extraction
x=ds.drop('Legendary',axis=1)
y=ds['Legendary']

In [19]:
#split data into testing and training
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2)

# Model Selection
* Load different models and check their accuracy to check the best model to make predictions on the data.

#1. Logistic Regression

In [20]:
#load the model
log_model=LogisticRegression()

#train the model
log_model.fit(x_train,y_train)

#make predictions
predictions=log_model.predict(x_test)

#evaluate the model
accuracy_score(y_test,predictions)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

1.0

# Findings
* Logistic regression accuracy is 100%

#2. KNN

In [21]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
predictions=knn.predict(x_test)
accuracy_score(y_test,predictions)

0.9397590361445783

# Findings
* KNN accuracy is 94%

#3. Decision Tree

In [23]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
predictions=dt.predict(x_test)
accuracy_score(y_test,predictions)

1.0

# Findings
* Decision tree has an accuracy of 100%

#ALGORITHM RECOMMENDATION
* Logistic regresion and decision Tree are the best algorithms to make predictions on whether a pokemon is Legendary or not.